### ISSUE TITLE
Can cinema4d_cpp_sdk generate  3d models automatically based on the vertexs?

### ISSUE THREAD

**Issue by giskook** [PluginCafe/cinema4d_cpp_sdk#1]
Hello,
    I have a demand.I hope I can generate 3d models automatically based on vertexs.Do cinema4d_cpp_sdk helps?
Thanks,
zhangkai

**Comment by Remotion** [comment]
Hi,
cinema4d_cpp_sdk is a collection of example / demo plugins for Maxon C4D.

> generate 3d models automatically based on vertexs
Do you mean generate polygonal object based on disconnected point cloud ? 
Any way something like this is not possible with this examples.

Remo
