### ISSUE TITLE
'c4d.h' file not found

### ISSUE THREAD

**Issue by bonsak** [PluginCafe/cinema4d_cpp_sdk#2]
In the include xcode project i have re-added:
"/Applications/Maxon/16.050/frameworks/settings/debugbase.xcconfig"
"/Applications/Maxon/16.050/frameworks/settings/releasebase.xcconfig"
"/Applications/Maxon/16.050/frameworks/cinema.framework/project/cinema.framework.xcodeproj"
But i still get "/Applications/Maxon/16.050/plugins/cinema4d_cpp_sdk-master/source/main.cpp:25:10: 'c4d.h' file not found" after xcode has indexed the project.
Even if c4d.h can be found in the project: "lib/source/c4d.h"

Whats the trick?

**Comment by SebastianBach** [comment]
Hello,

I could not reproduce any problems setting up the project or compiling it on OSX. If the problem persists and you need help to setup Xcode or your project you might want to come over to the PluginCafe (http://www.plugincafe.com/forum/default.asp) were we could help you better.

best wishes,
Sebastian

**Comment by bonsak** [comment]
Turns out the sdk folder you download from this repo (cinema4d_cpp_sdk-master) has to be put inside another folder in the plugins folder to work right away. (plugins/somefolder/cinema4d_cpp_sdk-master)

The sdk that comes with cinema R16 will work if its placed directly in the plugins folder.
The reason for this is that the constant "MAXON_ROOTDIR" is defined as "../../../" in this repo, 
but is defined as "../../" in the xcode project that comes with R16.

So if you place this repo directly in the plugins folder it can't find "debugbase", "releasebase" and "cinema.framework.xcodeproj" as its looking for these files one directory to high up.
I tried changing "MAXON_ROOTDIR" to "../../" and re-add the 3 files mentioned but there must be some other things i need to change as i still get an error that it can't find "c4d.h"

**Comment by SebastianBach** [comment]
Hello,

I cannot confirm your report. Using the ZIP file with R16.050 I have no problems whatsoever building the examples. If you need help please head over to the PluginCafe.

best wishes,
Sebastian

**Comment by donovankeith** [comment]
I ran into the same problem. I'm retrieving the Repo using Git via XCode. Thanks @bonsak for the workaround, copying the repo to "githubsdk" inside of "plugins" allowed the build to succeed.

**Comment by donovankeith** [comment]
These are the errors I get when placing `cinema4d_cpp_sdk` directly in the `plugins` folder when trying to build.

![image](https://cloud.githubusercontent.com/assets/4267389/9534396/f56e90ec-4ccc-11e5-867d-3e691397b1e3.png)

**Comment by Valkaari** [comment]
The C4D_ROOTDIR folder is set to ../.. 
From plugins directory, it's pointing to /Applications/Maxon/
You should either change it in xcode or use a sub-folder in the plugin directory (something like Dev)

So plugins/Dev/cinema4Dsdk/
It should found the frameworks directory after that.

**Comment by bonsak** [comment]
Then i think this repo should reflect that. Either put the whole sdk in a "dev" folder or fix the ROOT_DIR in the xcode project.

**Comment by andreasblock** [comment]
Hi guys,
we'll update the project files soon. It is planned in parallel with R17 release. May be we need a bit more time. But we are on it.
Bye,
Andreas
