### ISSUE TITLE
SDK doesn't build in R17

### ISSUE THREAD

**Issue by donovankeith** [PluginCafe/cinema4d_cpp_sdk#3]
Using XCode 6.4 w/ Cinema 4D R17 (equivalent to the Demo) - I am unable to successfully build the SDK example projects in a way that loads into C4D.

Can you create a branch of this repo for the R17 SDK so that we can start developing plugins for the latest version?

**Comment by SebastianBach** [comment]
Hello,

we will update this branch to R17 with the release of Cinema 4D R17 next week. But you can download the SDK example project also with the R17 demo.

Best wishes,
Sebastian
